pub const ScriptError = error{
    Overflow,
    UnsupportedLockingScript,
    InvalidPushData,
    ScriptTooBig,
    ElementTooBig,
    InvalidUnlockingScript,
    StackUnderflow,
    AltStackUnderflow,
    InvalidStackIndex,
    InvalidOperandSize,
    InvalidSplitPosition,
    NegativeShift,
    DivisionByZero,
    VerifyFailed,
    ReturnEncountered,
    UnexpectedElse,
    UnexpectedEndIf,
    UnbalancedConditionals,
    OpCountLimitExceeded,
    StackSizeLimitExceeded,
    MissingChecksigContext,
    InvalidMultisigKeyCount,
    InvalidMultisigSignatureCount,
    NullDummy,
    NullFail,
    SigPushOnly,
    CleanStack,
    MinimalData,
    MinimalIf,
    DiscourageUpgradableNops,
    IllegalForkId,
    InvalidSigHashType,
    HighS,
    UnknownOpcode,
    InvalidSignatureEncoding,
    InvalidPublicKeyEncoding,
    InvalidEncoding,
    NonMinimalEncoding,
    NumberTooBig,
    NegativeLockTime,
    UnsatisfiedLockTime,
    /// A flag combination the engine refuses: `utxo_after_chronicle` without
    /// `utxo_after_genesis` (go-sdk thread.go: ErrInvalidFlags,
    /// "UTXOAfterChronicle requires UTXOAfterGenesis").
    InvalidFlags,
};
