// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#include "program.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `skein:kernel/skein@0.1.0`

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("input")))
extern void __wasm_import_skein_kernel_skein_input(uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("get")))
extern void __wasm_import_skein_kernel_skein_get(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("put")))
extern void __wasm_import_skein_kernel_skein_put(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("putblock")))
extern void __wasm_import_skein_kernel_skein_putblock(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("keep")))
extern void __wasm_import_skein_kernel_skein_keep(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("launch")))
extern void __wasm_import_skein_kernel_skein_launch(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("await")))
extern void __wasm_import_skein_kernel_skein_await(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("head")))
extern void __wasm_import_skein_kernel_skein_head(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("advance")))
extern void __wasm_import_skein_kernel_skein_advance(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("wallet")))
extern void __wasm_import_skein_kernel_skein_wallet(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("emit")))
extern void __wasm_import_skein_kernel_skein_emit(uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("deadline")))
extern void __wasm_import_skein_kernel_skein_deadline(int64_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("call")))
extern void __wasm_import_skein_kernel_skein_call(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("skein:kernel/skein@0.1.0"), __import_name__("edges")))
extern void __wasm_import_skein_kernel_skein_edges(uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void skein_kernel_skein_cid_free(skein_kernel_skein_cid_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void program_list_u8_free(program_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void skein_kernel_skein_result_list_u8_string_free(skein_kernel_skein_result_list_u8_string_t *ptr) {
  if (!ptr->is_err) {
    program_list_u8_free(&ptr->val.ok);
  } else {
    program_string_free(&ptr->val.err);
  }
}

void skein_kernel_skein_result_cid_string_free(skein_kernel_skein_result_cid_string_t *ptr) {
  if (!ptr->is_err) {
    skein_kernel_skein_cid_free(&ptr->val.ok);
  } else {
    program_string_free(&ptr->val.err);
  }
}

void skein_kernel_skein_result_void_string_free(skein_kernel_skein_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    program_string_free(&ptr->val.err);
  }
}

void skein_kernel_skein_option_cid_free(skein_kernel_skein_option_cid_t *ptr) {
  if (ptr->is_some) {
    skein_kernel_skein_cid_free(&ptr->val);
  }
}

void skein_kernel_skein_result_option_cid_string_free(skein_kernel_skein_result_option_cid_string_t *ptr) {
  if (!ptr->is_err) {
    skein_kernel_skein_option_cid_free(&ptr->val.ok);
  } else {
    program_string_free(&ptr->val.err);
  }
}

void program_option_string_free(program_option_string_t *ptr) {
  if (ptr->is_some) {
    program_string_free(&ptr->val);
  }
}

void program_string_set(program_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void program_string_dup(program_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void program_string_dup_n(program_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void program_string_free(program_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void skein_kernel_skein_input(program_list_u8_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_input(ptr);
  *ret = (program_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

bool skein_kernel_skein_get(skein_kernel_skein_cid_t *cid, program_list_u8_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_get((uint8_t *) (*cid).ptr, (*cid).len, ptr);
  skein_kernel_skein_result_list_u8_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (program_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_put(program_list_u8_t *data, skein_kernel_skein_cid_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_put((uint8_t *) (*data).ptr, (*data).len, ptr);
  skein_kernel_skein_result_cid_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (skein_kernel_skein_cid_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_putblock(skein_kernel_skein_cid_t *cid, program_list_u8_t *data, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_putblock((uint8_t *) (*cid).ptr, (*cid).len, (uint8_t *) (*data).ptr, (*data).len, ptr);
  skein_kernel_skein_result_void_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_keep(skein_kernel_skein_cid_t *cid, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_keep((uint8_t *) (*cid).ptr, (*cid).len, ptr);
  skein_kernel_skein_result_void_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_launch(skein_kernel_skein_cid_t *program, skein_kernel_skein_cid_t *args, skein_kernel_skein_cid_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_launch((uint8_t *) (*program).ptr, (*program).len, (uint8_t *) (*args).ptr, (*args).len, ptr);
  skein_kernel_skein_result_cid_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (skein_kernel_skein_cid_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_await(skein_kernel_skein_cid_t *cid, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_await((uint8_t *) (*cid).ptr, (*cid).len, ptr);
  skein_kernel_skein_result_void_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_head(program_string_t *name, skein_kernel_skein_option_cid_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(4*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_head((uint8_t *) (*name).ptr, (*name).len, ptr);
  skein_kernel_skein_result_option_cid_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      skein_kernel_skein_option_cid_t option;
      switch ((int32_t) *((uint8_t*) (ptr + sizeof(void*)))) {
        case 0: {
          option.is_some = false;
          break;
        }
        case 1: {
          option.is_some = true;
          option.val = (skein_kernel_skein_cid_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.ok = option;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_advance(program_string_t *name, skein_kernel_skein_cid_t *tree, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_advance((uint8_t *) (*name).ptr, (*name).len, (uint8_t *) (*tree).ptr, (*tree).len, ptr);
  skein_kernel_skein_result_void_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_wallet(program_list_u8_t *frame, program_list_u8_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_wallet((uint8_t *) (*frame).ptr, (*frame).len, ptr);
  skein_kernel_skein_result_list_u8_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (program_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_emit(program_list_u8_t *message, skein_kernel_skein_cid_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_emit((uint8_t *) (*message).ptr, (*message).len, ptr);
  skein_kernel_skein_result_cid_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (skein_kernel_skein_cid_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_deadline(int64_t until_ms, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_deadline(until_ms, ptr);
  skein_kernel_skein_result_void_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_call(skein_kernel_skein_cid_t *program, program_string_t *fn, program_list_u8_t *arg, program_list_u8_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_call((uint8_t *) (*program).ptr, (*program).len, (uint8_t *) (*fn).ptr, (*fn).len, (uint8_t *) (*arg).ptr, (*arg).len, ptr);
  skein_kernel_skein_result_list_u8_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (program_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool skein_kernel_skein_edges(skein_kernel_skein_cid_t *to, program_string_t *maybe_rel, program_list_u8_t *ret, program_string_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  program_option_string_t rel;
  rel.is_some = maybe_rel != NULL;if (maybe_rel) {
    rel.val = *maybe_rel;
  }
  int32_t option;
  uint8_t * option1;
  size_t option2;
  if ((rel).is_some) {
    const program_string_t *payload0 = &(rel).val;
    option = 1;
    option1 = (uint8_t *) (*payload0).ptr;
    option2 = (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_skein_kernel_skein_edges((uint8_t *) (*to).ptr, (*to).len, option, option1, option2, ptr);
  skein_kernel_skein_result_list_u8_string_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (program_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (program_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_program(void);
__attribute__((used))
void __component_type_object_force_link_program_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_program();
}
