// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#ifndef __BINDINGS_PROGRAM_H
#define __BINDINGS_PROGRAM_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct program_string_t {
  uint8_t*ptr;
  size_t len;
} program_string_t;

// A CID in its binary form.
typedef struct skein_kernel_skein_cid_t {
  uint8_t   *ptr;
  size_t len;
} skein_kernel_skein_cid_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} program_list_u8_t;

typedef struct {
  bool is_err;
  union {
    program_list_u8_t ok;
    program_string_t err;
  } val;
} skein_kernel_skein_result_list_u8_string_t;

typedef struct {
  bool is_err;
  union {
    skein_kernel_skein_cid_t ok;
    program_string_t err;
  } val;
} skein_kernel_skein_result_cid_string_t;

typedef struct {
  bool is_err;
  union {
    program_string_t err;
  } val;
} skein_kernel_skein_result_void_string_t;

typedef struct {
  bool is_some;
  skein_kernel_skein_cid_t val;
} skein_kernel_skein_option_cid_t;

typedef struct {
  bool is_err;
  union {
    skein_kernel_skein_option_cid_t ok;
    program_string_t err;
  } val;
} skein_kernel_skein_result_option_cid_string_t;

typedef struct {
  bool is_some;
  program_string_t val;
} program_option_string_t;

// Imported Functions from `skein:kernel/skein@0.1.0`
// The step's input record (dag-cbor).
extern void skein_kernel_skein_input(program_list_u8_t *ret);
// A record's bytes.
extern bool skein_kernel_skein_get(skein_kernel_skein_cid_t *cid, program_list_u8_t *ret, program_string_t *err);
// Store dag-cbor (re-encoded canonically); its CID.
extern bool skein_kernel_skein_put(program_list_u8_t *data, skein_kernel_skein_cid_t *ret, program_string_t *err);
// Store bytes under a CID minted elsewhere; the hash is checked. Besides
// dag-cbor/raw with sha2-256, `bitcoin-tx` and `bitcoin-block` with
// dbl-sha2-256 (#29).
extern bool skein_kernel_skein_putblock(skein_kernel_skein_cid_t *cid, program_list_u8_t *data, program_string_t *err);
// Keep a stored record in the thread's state: listed in this step's update
// (`kept`), so later steps find it from the tip.
extern bool skein_kernel_skein_keep(skein_kernel_skein_cid_t *cid, program_string_t *err);
// Open a thread running `program` (a program record) on `args` (a record);
// its origin CID.
extern bool skein_kernel_skein_launch(skein_kernel_skein_cid_t *program, skein_kernel_skein_cid_t *args, skein_kernel_skein_cid_t *ret, program_string_t *err);
// An outbound message: an emit record carrying the complete envelope,
// signed and encrypted by the program through `wallet`; checked, not
// attested; its signed part's record CID. Handed on when the step ends.
extern bool skein_kernel_skein_emit(skein_kernel_skein_cid_t *cid, skein_kernel_skein_cid_t *ret, program_string_t *err);
// Rest on a reply to an envelope this step emitted (the step ends
// `waiting` with `awaits`; an admitted envelope whose body's `replyTo` is
// that CID is the thread's next input), or on a record in the store: the
// subject of a plain entry to come (#29).
extern bool skein_kernel_skein_await(skein_kernel_skein_cid_t *cid, program_string_t *err);
// A handle "handle@domain" → the resolver's whole answer (dag-cbor
// {identityKey, …}). Attested: the host's resolver answers, the answer is
// recorded; replay reads the record.
extern bool skein_kernel_skein_resolve(program_string_t *name, program_list_u8_t *ret, program_string_t *err);
// The tree CID a named head points at; none if it has none (preview1:
// n = 0). docs/VM.md "Heads".
extern bool skein_kernel_skein_head(program_string_t *name, skein_kernel_skein_option_cid_t *ret, program_string_t *err);
// Move a named head to a tree in the store, when the step ends without error.
extern bool skein_kernel_skein_advance(program_string_t *name, skein_kernel_skein_cid_t *tree, program_string_t *err);
// Change the subscriptions (docs/VM.md "Subscriptions"): `op` "add" or
// "remove" the rule (sender, box) → handler (a program record in the
// store; no sender: any sender), when the step ends without error.
extern bool skein_kernel_skein_subscribe(program_string_t *op, program_string_t *maybe_sender, program_string_t *box, skein_kernel_skein_cid_t *handler, program_string_t *err);
// A BRC-100 wallet wire request frame → its result frame. Attested.
extern bool skein_kernel_skein_wallet(program_list_u8_t *frame, program_list_u8_t *ret, program_string_t *err);
// One HTTP request, dag-cbor {method, url, headers?, body?} → the response
// {status, headers, body}, answered by the host and attested (op "http").
// The pre-#15 shape: #15 replaces it with standard `wasi:http`
// (`wasi:http/outgoing-handler`), answered and recorded the same way; the
// world below then imports that instead.
extern bool skein_kernel_skein_http(program_list_u8_t *request, program_list_u8_t *ret, program_string_t *err);
// If this step ends waiting, rest no later than `until-ms` (ms since the
// epoch, after the step's time): a wake entry then steps the thread (#29).
extern bool skein_kernel_skein_deadline(int64_t until_ms, program_string_t *err);

// Helper Functions

void skein_kernel_skein_cid_free(skein_kernel_skein_cid_t *ptr);

void program_list_u8_free(program_list_u8_t *ptr);

void skein_kernel_skein_result_list_u8_string_free(skein_kernel_skein_result_list_u8_string_t *ptr);

void skein_kernel_skein_result_cid_string_free(skein_kernel_skein_result_cid_string_t *ptr);

void skein_kernel_skein_result_void_string_free(skein_kernel_skein_result_void_string_t *ptr);

void skein_kernel_skein_option_cid_free(skein_kernel_skein_option_cid_t *ptr);

void skein_kernel_skein_result_option_cid_string_free(skein_kernel_skein_result_option_cid_string_t *ptr);

void program_option_string_free(program_option_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void program_string_set(program_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void program_string_dup(program_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void program_string_dup_n(program_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void program_string_free(program_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
