// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#ifndef __BINDINGS_PROGRAM_H
#define __BINDINGS_PROGRAM_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct program_string_t {
  uint8_t*ptr;
  size_t len;
} program_string_t;

// A CID in its binary form.
typedef struct skein_kernel_skein_cid_t {
  uint8_t   *ptr;
  size_t len;
} skein_kernel_skein_cid_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} program_list_u8_t;

typedef struct {
  bool is_err;
  union {
    program_list_u8_t ok;
    program_string_t err;
  } val;
} skein_kernel_skein_result_list_u8_string_t;

typedef struct {
  bool is_err;
  union {
    skein_kernel_skein_cid_t ok;
    program_string_t err;
  } val;
} skein_kernel_skein_result_cid_string_t;

typedef struct {
  bool is_err;
  union {
    program_string_t err;
  } val;
} skein_kernel_skein_result_void_string_t;

typedef struct {
  bool is_some;
  skein_kernel_skein_cid_t val;
} skein_kernel_skein_option_cid_t;

typedef struct {
  bool is_err;
  union {
    skein_kernel_skein_option_cid_t ok;
    program_string_t err;
  } val;
} skein_kernel_skein_result_option_cid_string_t;

typedef struct {
  bool is_some;
  program_string_t val;
} program_option_string_t;

// Imported Functions from `skein:kernel/skein@0.1.0`
// The step's input record (dag-cbor).
extern void skein_kernel_skein_input(program_list_u8_t *ret);
// A record's bytes.
extern bool skein_kernel_skein_get(skein_kernel_skein_cid_t *cid, program_list_u8_t *ret, program_string_t *err);
// Store dag-cbor (re-encoded canonically); its CID.
extern bool skein_kernel_skein_put(program_list_u8_t *data, skein_kernel_skein_cid_t *ret, program_string_t *err);
// Store bytes under a CID minted elsewhere; the hash is checked. Besides
// dag-cbor/raw with sha2-256, `bitcoin-tx` and `bitcoin-block` with
// dbl-sha2-256 (#29).
extern bool skein_kernel_skein_putblock(skein_kernel_skein_cid_t *cid, program_list_u8_t *data, program_string_t *err);
// Keep a stored record in the thread's state: listed in this step's update
// (`kept`), so later steps find it from the tip.
extern bool skein_kernel_skein_keep(skein_kernel_skein_cid_t *cid, program_string_t *err);
// Open a thread running `program` (a program record) on `args` (a record);
// its origin CID.
extern bool skein_kernel_skein_launch(skein_kernel_skein_cid_t *program, skein_kernel_skein_cid_t *args, skein_kernel_skein_cid_t *ret, program_string_t *err);
// Rest on a record in the store (the step ends `waiting` with `awaits`):
// a message this step emitted (#70: an admitted message whose body's
// `replyTo` names it, from the identity it was sent to, is the thread's
// next input), a thread (#66), or the subject of a plain entry to come (#29).
extern bool skein_kernel_skein_await(skein_kernel_skein_cid_t *cid, program_string_t *err);
// The tree CID a named head points at; none if it has none (preview1:
// n = 0). docs/VM.md "Heads".
extern bool skein_kernel_skein_head(program_string_t *name, skein_kernel_skein_option_cid_t *ret, program_string_t *err);
// Move a named head to a tree in the store, when the step ends without
// error. The name must be in the program's write scope (shruggr/skein#77:
// an app's heads are `<app>/…`; a genesis-wired program's are what its
// genesis `scopes` name). There is no `subscribe`: the dispatch table is
// the kernel's (docs/MESSAGES.md).
extern bool skein_kernel_skein_advance(program_string_t *name, skein_kernel_skein_cid_t *tree, program_string_t *err);
// A BRC-100 wallet wire request frame → its result frame: the signer,
// answered synchronously and recorded (an `oracle` record on the update —
// the record's kind keeps the signer's old name).
extern bool skein_kernel_skein_wallet(program_list_u8_t *frame, program_list_u8_t *ret, program_string_t *err);
// The one outbound primitive (#70): emit a signed message. `message` is
// dag-cbor {to: bytes(33), box, body: <dag-cbor bytes>, subject?: <cid>};
// the result is the message's CID. `to` must be in the address book (the
// head `peers`); the kernel signs the message through the signer, lists
// it on the step's update (`emitted`) and sends it by the recipient's
// transport when the step ends without error. The answer is an entry:
// `await` the CID and end the step. docs/VM.md, "emit".
extern bool skein_kernel_skein_emit(program_list_u8_t *message, skein_kernel_skein_cid_t *ret, program_string_t *err);
// If this step ends waiting, rest no later than `until-ms` (ms since the
// epoch, after the step's time): an intention (shruggr/skein#126) — the
// kernel records a `deadline` event on the step, which it awaits; the
// runtime's answer at that time steps the thread with `woke`.
extern bool skein_kernel_skein_deadline(int64_t until_ms, program_string_t *err);
// A BRC-104 request from this instance (shruggr/skein#126): `request` is
// dag-cbor {url: <the server's base URL>, method?, path?, headers?: {name:
// text}, body?: bytes, timeoutMs?}; the result is dag-cbor {status,
// headers, body}. The kernel holds the BRC-103 session with the server,
// signs the request and checks the answer through the signer, and the
// runtime moves the bytes; the exchange is a recorded call on the step.
// No answer at all is an error starting "transient: ". The one direct
// HTTP path a program has.
extern bool skein_kernel_skein_authfetch(program_list_u8_t *request, program_list_u8_t *ret, program_string_t *err);
// An in-VM call (#40): run `program` (a program record) as a function —
// its entry, with `input()` = {kind: "call", fn, arg, …} — and return what
// it wrote to stdout (a non-zero exit is the error, its last stderr line).
// From a step, the callee is part of the step (its recorded calls, records
// and head moves are the step's); from the kernel's `call`, it only reads.
extern bool skein_kernel_skein_call(skein_kernel_skein_cid_t *program, program_string_t *fn, program_list_u8_t *arg, program_list_u8_t *ret, program_string_t *err);
// The edges into a record (#42): who points at `to`, from the kernel's
// index, `rel` only if given — dag-cbor [{from, seq, rel, locator}] in key
// order (from, seq, ord). Who spent txid:vout is `spends` into the
// transaction's CID with locator = vout (from each kept spending
// transaction, seq 0). A read, a pure function of the log plus the
// bitcoin blocks this step kept so far.
extern bool skein_kernel_skein_edges(skein_kernel_skein_cid_t *to, program_string_t *maybe_rel, program_list_u8_t *ret, program_string_t *err);

// Helper Functions

void skein_kernel_skein_cid_free(skein_kernel_skein_cid_t *ptr);

void program_list_u8_free(program_list_u8_t *ptr);

void skein_kernel_skein_result_list_u8_string_free(skein_kernel_skein_result_list_u8_string_t *ptr);

void skein_kernel_skein_result_cid_string_free(skein_kernel_skein_result_cid_string_t *ptr);

void skein_kernel_skein_result_void_string_free(skein_kernel_skein_result_void_string_t *ptr);

void skein_kernel_skein_option_cid_free(skein_kernel_skein_option_cid_t *ptr);

void skein_kernel_skein_result_option_cid_string_free(skein_kernel_skein_result_option_cid_string_t *ptr);

void program_option_string_free(program_option_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void program_string_set(program_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void program_string_dup(program_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void program_string_dup_n(program_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void program_string_free(program_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
